import "./globals.css";
import type { Metadata } from "next";

// Default metadata for the entire application
export const metadata: Metadata = {
  title: "Rock Paper Scissors Game in Next.js",
  description: "Generated by Gurgant",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="night-mode">{children}</body>
    </html>
  );
}
